# Generated by Django 5.1.2 on 2024-10-25 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenue',
            fields=[
                ('idtenu', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.IntegerField()),
                ('avance', models.IntegerField()),
                ('reste', models.IntegerField()),
                ('modele', models.TextField()),
                ('description', models.CharField(max_length=300)),
                ('ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('idcom', models.AutoField(primary_key=True, serialize=False)),
                ('debutcom', models.DateTimeField()),
                ('fincom', models.DateTimeField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('idclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coutureApp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('idfacture', models.AutoField(primary_key=True, serialize=False)),
                ('montantdonne', models.IntegerField()),
                ('montantfacture', models.IntegerField()),
                ('reste', models.IntegerField()),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('idclient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coutureApp.client')),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coutureApp.commande')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModele',
            fields=[
                ('idmg', models.AutoField(primary_key=True, serialize=False)),
                ('photos', models.BinaryField()),
                ('libelle', models.CharField(max_length=100)),
                ('ajout', models.DateTimeField(auto_now_add=True)),
                ('idtenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coutureApp.tenue')),
            ],
        ),
        migrations.CreateModel(
            name='TenueCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coutureApp.commande')),
                ('idtenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coutureApp.tenue')),
            ],
            options={
                'unique_together': {('idcom', 'idtenu')},
            },
        ),
    ]
