# Generated by Django 5.1.2 on 2024-11-07 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenue',
            name='idcom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coutureApp.commande'),
        ),
        migrations.DeleteModel(
            name='TenueCommande',
        ),
    ]
