# Generated by Django 5.1.2 on 2024-11-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0002_tenue_idcom_delete_tenuecommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodele',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='tenue_images/'),
        ),
    ]
