# Generated by Django 5.1.2 on 2024-11-13 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0003_alter_imagemodele_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenue',
            name='etat_tenue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenue',
            name='modifierle',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commande',
            name='debutcom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fincom',
            field=models.DateField(),
        ),
    ]
