# Generated by Django 5.1.2 on 2024-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0004_tenue_etat_tenue_tenue_modifierle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montantdonne',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montantfacture',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='reste',
        ),
        migrations.AddField(
            model_name='commande',
            name='montantcom',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tenue',
            name='montant',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tenue',
            name='qte',
            field=models.IntegerField(default=1),
        ),
    ]
