# Generated by Django 5.1.2 on 2024-11-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0005_remove_facture_montantdonne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='En Attente', max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='montantcom',
            field=models.IntegerField(default=0),
        ),
    ]
