# Generated by Django 5.1.2 on 2024-11-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0006_commande_statut_alter_commande_montantcom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenue',
            name='montant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tenue',
            name='qte',
            field=models.IntegerField(default=0),
        ),
    ]
