# Generated by Django 5.1.2 on 2024-11-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0007_alter_tenue_montant_alter_tenue_qte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='En Cours', max_length=50),
        ),
    ]
