# Generated by Django 5.1.2 on 2024-11-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0008_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='En Cours', max_length=51),
        ),
    ]
