# Generated by Django 5.1.3 on 2024-12-06 19:35

import coutureApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0009_alter_commande_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='idclient',
            field=models.AutoField(default=coutureApp.models.generate_client_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
