# Generated by Django 5.1.3 on 2024-12-06 20:59

import coutureApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0010_alter_client_idclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='idcom',
            field=models.AutoField(default=coutureApp.models.generate_commande_id, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='idfacture',
            field=models.AutoField(default=coutureApp.models.generate_facture_id, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imagemodele',
            name='idmg',
            field=models.AutoField(default=coutureApp.models.generate_image_id, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tenue',
            name='idtenu',
            field=models.AutoField(default=coutureApp.models.generate_tenue_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
