# Generated by Django 5.1.3 on 2024-12-06 21:12

import coutureApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0011_alter_commande_idcom_alter_facture_idfacture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='idclient',
            field=models.CharField(default=coutureApp.models.generate_client_id, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='idcom',
            field=models.CharField(default=coutureApp.models.generate_commande_id, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='idfacture',
            field=models.CharField(default=coutureApp.models.generate_facture_id, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='imagemodele',
            name='idmg',
            field=models.CharField(default=coutureApp.models.generate_image_id, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tenue',
            name='idtenu',
            field=models.CharField(default=coutureApp.models.generate_tenue_id, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
