# Generated by Django 5.1.3 on 2024-12-17 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0012_alter_client_idclient_alter_commande_idcom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='idclient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandeclient', to='coutureApp.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='idclient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factureclient', to='coutureApp.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='idcom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturecommande', to='coutureApp.commande'),
        ),
        migrations.AlterField(
            model_name='imagemodele',
            name='idtenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagetenue', to='coutureApp.tenue'),
        ),
        migrations.AlterField(
            model_name='tenue',
            name='idcom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenuecommandee', to='coutureApp.commande'),
        ),
    ]
