# Generated by Django 5.1.3 on 2025-01-13 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0013_alter_commande_idclient_alter_facture_idclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='dateretrait',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commande',
            name='idclient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coutureApp.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='idclient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coutureApp.client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='idcom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coutureApp.commande'),
        ),
        migrations.AlterField(
            model_name='imagemodele',
            name='idtenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coutureApp.tenue'),
        ),
        migrations.AlterField(
            model_name='tenue',
            name='idcom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coutureApp.commande'),
        ),
    ]
