# Generated by Django 5.1.3 on 2025-01-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0015_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
