# Generated by Django 5.1.3 on 2025-02-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0017_alter_client_options_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_facture',
            field=models.DateTimeField(),
        ),
    ]
