# Generated by Django 5.1.3 on 2025-02-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0018_alter_facture_date_facture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='nom_prenom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='creation',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='idclient',
        ),
        migrations.RemoveField(
            model_name='imagemodele',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='tenue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tenue',
            name='modifierle',
        ),
        migrations.AddField(
            model_name='client',
            name='sexe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='methodePayement',
            field=models.CharField(default='Espece', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='debutcom',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fincom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_facture',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenue',
            name='montant',
            field=models.IntegerField(default=models.IntegerField()),
        ),
        migrations.AlterField(
            model_name='tenue',
            name='qte',
            field=models.IntegerField(default=1),
        ),
    ]
