# Generated by Django 5.1.3 on 2025-02-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0019_rename_nom_client_nom_prenom_remove_client_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='debutcom',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fincom',
            field=models.DateField(),
        ),
    ]
