# Generated by Django 5.1.3 on 2025-02-13 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coutureApp', '0020_alter_commande_debutcom_alter_commande_fincom'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
